<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox</name>
   <tag></tag>
   <elementGuidId>df76545c-9c3b-41a4-9e78-ae7a8714f9c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt127_block_wtContent_wtCheckBoxPSA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt127_block_wtContent_wtCheckBoxPSA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt156$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$wtListRecordPSA$ctl00$OutSystemsUIWeb_wt63$block$wtContent$OutSystemsUIWeb_wt127$block$wtContent$wtCheckBoxPSA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt127_block_wtContent_wtCheckBoxPSA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>28</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wt139', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt127_block_wtContent_wtCheckBoxPSA','wt156$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$wtListRecordPSA$ctl00$OutSystemsUIWeb_wt63$block$wtContent$OutSystemsUIWeb_wt127$block$wtContent$wtCheckBoxPSA','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt127_block_wtContent_wtCheckBoxPSA&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt127_block_wtContent_wtCheckBoxPSA']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt127_block_wtContent']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
