<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_System AnalystQuantity</name>
   <tag></tag>
   <elementGuidId>ead1e9b2-3a77-4862-9d21-c5768868f73b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>center-align flex-direction-row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>System AnalystQuantity</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PSA'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resource Needs'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div</value>
   </webElementXpaths>
</WebElementEntity>
