<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Quantity_wt156_OutSystemsUIWeb_wt4_blo_4f10e8</name>
   <tag></tag>
   <elementGuidId>297d86b0-6cb0-41b9-91cc-a2386f5c76a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt117_block_wtContent_wtInputQuantityPSAAjaxRfrsh']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt117_block_wtContent_wtInputQuantityPSAAjaxRfrsh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt117_block_wtContent_wtInputQuantityPSAAjaxRfrsh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt117_block_wtContent_wtInputQuantityPSAAjaxRfrsh&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt117_block_wtContent_wtInputQuantityPSAAjaxRfrsh']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt156_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtListRecordPSA_ctl00_OutSystemsUIWeb_wt63_block_wtContent_OutSystemsUIWeb_wt117_block_wtContent']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]//span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Analyst'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Manager'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[2]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/div/span</value>
   </webElementXpaths>
</WebElementEntity>
