<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_Something went wrong, please try again later</name>
   <tag></tag>
   <elementGuidId>e0e94350-b137-41a5-8c68-fc8c078e5059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Feedback_Message_Error</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Something went wrong, please try again later' or . = 'Something went wrong, please try again later')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OutSystemsUIWeb_wt16_block_wt4_RichWidgets_wt7_block_wtFeedback_Wrapper']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Feedback_Message_Error</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Something went wrong, please try again later</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OutSystemsUIWeb_wt16_block_wt4_RichWidgets_wt7_block_wtFeedback_Wrapper&quot;)/div[@class=&quot;Feedback_Message_Error&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OutSystemsUIWeb_wt16_block_wt4_RichWidgets_wt7_block_wtFeedback_Wrapper']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC MVP  - CMS Monitoring'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
   </webElementXpaths>
</WebElementEntity>
