<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_Password confirmation does not match</name>
   <tag></tag>
   <elementGuidId>5d00af9b-f5b4-4c03-aca0-792d99b8152b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Feedback_Message_Error</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Password confirmation does not match!' or . = 'Password confirmation does not match!')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wt17_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtFeedback_Wrapper']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Feedback_Message_Error</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password confirmation does not match!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt17_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtFeedback_Wrapper&quot;)/div[@class=&quot;Feedback_Message_Error&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt17_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtFeedback_Wrapper']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Content (Press Enter)'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
   </webElementXpaths>
</WebElementEntity>
