<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NPK  Email_OutSystemsUIWeb_wt16blockw_ebc43a</name>
   <tag></tag>
   <elementGuidId>b3d93da2-853b-4a86-823c-cefc49fc082b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OutSystemsUIWeb_wt16_block_wtLogin_OutSystemsUIWeb_wt19_block_wtLogin_OutSystemsUIWeb_wt31_block_wtInput_wtUserNameInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OutSystemsUIWeb_wt16_block_wtLogin_OutSystemsUIWeb_wt19_block_wtLogin_OutSystemsUIWeb_wt31_block_wtInput_wtUserNameInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OutSystemsUIWeb_wt16$block$wtLogin$OutSystemsUIWeb_wt19$block$wtLogin$OutSystemsUIWeb_wt31$block$wtInput$wtUserNameInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OutSystemsUIWeb_wt16_block_wtLogin_OutSystemsUIWeb_wt19_block_wtLogin_OutSystemsUIWeb_wt31_block_wtInput_wtUserNameInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('OutSystemsUIWeb_wt16_block_wtLogin_OutSystemsUIWeb_wt19_block_wtLogin_wt15', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OutSystemsUIWeb_wt16_block_wtLogin_OutSystemsUIWeb_wt19_block_wtLogin_OutSystemsUIWeb_wt31_block_wtInput_wtUserNameInput&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OutSystemsUIWeb_wt16_block_wtLogin_OutSystemsUIWeb_wt19_block_wtLogin_OutSystemsUIWeb_wt31_block_wtInput_wtUserNameInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OutSystemsUIWeb_wt16_block_wtLogin_OutSystemsUIWeb_wt19_block_wtLogin_OutSystemsUIWeb_wt31_block_wtInput']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
