<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cancel_reset</name>
   <tag></tag>
   <elementGuidId>97c8e070-61e3-4c26-9247-0ebe5df31b54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_OutSystemsUIWeb_wtresetpasswordmodal_block_wtFooter_wt33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_OutSystemsUIWeb_wtresetpasswordmodal_block_wtFooter_wt33']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_OutSystemsUIWeb_wtresetpasswordmodal_block_wtFooter_wt33','wt64$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$wtTableRecords$ctl05$OutSystemsUIWeb_wtresetpasswordmodal$block$wtFooter$wt33','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt64$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$wtTableRecords$ctl05$OutSystemsUIWeb_wtresetpasswordmodal$block$wtFooter$wt33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_OutSystemsUIWeb_wtresetpasswordmodal_block_wtFooter_wt33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_OutSystemsUIWeb_wtresetpasswordmodal_block_wtFooter_wt33&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_OutSystemsUIWeb_wtresetpasswordmodal_block_wtFooter_wt33']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_OutSystemsUIWeb_wtresetpasswordmodal_block_wtFooter']/div/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[8]/span/div/div/div[3]/div/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
