<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_delete</name>
   <tag></tag>
   <elementGuidId>a0aadc6d-50ad-4256-8eed-f2e98b7c2b72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_wt42 > span.fa.fa-fw.fa-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_wt42']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-trash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_wt42&quot;)/span[@class=&quot;fa fa-fw fa-trash&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_wt42']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[8]/a[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt52_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt34']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
