<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_active</name>
   <tag></tag>
   <elementGuidId>ee823efe-b305-49ff-8f29-9e8dc2c4078f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-toggle-off.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_wt100']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-toggle-off fa-2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_wt100&quot;)/span[@class=&quot;fa fa-fw fa-toggle-off fa-2x&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt64_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl05_wt100']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt52_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt84']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
