<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_delete</name>
   <tag></tag>
   <elementGuidId>dab13fa1-513e-40d3-815f-f7deda1cc790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/div/a[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-trash</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;wt34_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt40&quot;)/span[@class=&quot;fa fa-fw fa-trash&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-trash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt34_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt40&quot;)/span[@class=&quot;fa fa-fw fa-trash&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt34_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt40']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/a[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
