<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_template_admin</name>
   <tag></tag>
   <elementGuidId>069ce21b-4f28-4993-aeb3-d282008c1a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt66</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt66']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location.href='TemplateEmail.aspx?TextTemplate=Dear%2c+tesawdw%0d%0a%0d%0aSemoga+pesan+ini+menjumpai+dalam+keadaan+sehat+selalu%0d%0aSehubung+dengan+request+resource+Technocenter+pada+tanggal+2022-03-31+%2cdengan+Request+ID+REQ21312312313+diinformasikan+bahwa+karena%0d%0aketerbatasan+resource%2c+maka+kami+belum+bisa+support+untuk+project+tersebut.%0d%0a%0d%0aRegards%0d%0aTechnocenter&amp;StatusProject=2&amp;(Not.Licensed.For.Production)='; return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt11$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$wtTableRecords$ctl03$wt66</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Template</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt66</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>28</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt66&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords_ctl03_wt66']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords']/tbody/tr/td[6]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
